# ARB Zephyr sample configuration
#
# SPDX-License-Identifier: Apache-2.0

# Middleware
CONFIG_ARB=y
CONFIG_ARB_DISPATCH_THREAD=y

# Drivers used by the Zephyr HAL bindings
CONFIG_PWM=y
CONFIG_GPIO=y
CONFIG_SENSOR=y

# Misc
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_LOG=y
CONFIG_MAIN_STACK_SIZE=4096

# Enable to mirror topics onto a ROS2 network (requires micro-ROS module)
# CONFIG_ARB_MICRO_ROS_BRIDGE=y
